### ISSUE TITLE
Describe required queries

### ISSUE THREAD

**Issue by almutlue** [omnibenchmark/omnibenchmark-py#27]
Write/Describe all required queries especially for the summaries

**Comment by almutlue** [comment]
A start: https://hackmd.io/@aluetg/rkPP-5NHa

**Comment by imallona** [comment]
Adding signatures [here](https://github.com/omnibenchmark/internal_docs/blob/master/architecture/triplestore_queries.md)

**Comment by imallona** [comment]
Cancelled, https://github.com/omnibenchmark/internal_docs/commit/43f35f07737976631da6898d5153130129f7335a
